### ISSUE TITLE
Readme tester only works for files called... README

### ISSUE THREAD

**Issue by oliverbrooks** [orangemug/readme-tester#7]
I'm writing some documentation with code samples in.  

It would be nice to be able to use readme-tester for these, however it only works for files named README.md.

I'm wondering if you should just pass in the full path to the file.

``` js
readmeTester("/my/path/to/README.md");
```

It could perhaps default to `README.md` if no file extension is provided in the file path to maintain backwards compatability. 

What do you think?

**Comment by orangemug** [comment]
Sounds like a good idea. Do you want to give https://github.com/orangemug/readme-tester/pull/8 a try?
